name: Code Quality & Tests

on:
  push: ~
  pull_request: ~

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.9
      - name: Install gotestsum
        run: make install-gotestsum
      - name: Install revive
        run: go get -u github.com/mgechev/revive
      - name: go mod tidy
        run: go mod tidy
      - name: go mod vendor
        run: go mod vendor
      - name: Lint the code
        run: make lint
      - name: Vet the code
        run: make vet
      - name: Run unit tests
        run: make test-with-coverage
      - name: Upload test coverage to CodeClimate
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_TEST_REPORTER_ID }}
        with:
          prefix: github.com/sprak3000/go-glitch
